# Generated by Django 4.2.7 on 2025-09-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('professional_role', models.CharField(choices=[('legal', 'Legal Practitioner'), ('customs', 'Customs Agent'), ('both', 'Both')], max_length=10)),
                ('experience_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('experience_customs', models.CharField(blank=True, max_length=20, null=True)),
                ('province', models.CharField(choices=[('balochistan', 'Balochistan'), ('ict', 'ICT'), ('kpk', 'KPK'), ('punjab', 'Punjab'), ('sindh', 'Sindh')], max_length=20)),
                ('g1_iris_rating', models.CharField(blank=True, max_length=20)),
                ('g2_system_weaknesses', models.CharField(blank=True, max_length=3)),
                ('g2a_weaknesses_details', models.TextField(blank=True)),
                ('g3_iris_limitations', models.TextField(blank=True)),
                ('g4_challenged_groups', models.JSONField(default=list)),
                ('g5_clients_change', models.CharField(blank=True, max_length=30)),
                ('g6_fee_change', models.CharField(blank=True, max_length=30)),
                ('g7_digital_literacy_impact', models.CharField(blank=True, max_length=30)),
                ('g8_training_received', models.CharField(blank=True, max_length=50)),
                ('lp1_technical_issues', models.CharField(blank=True, max_length=30)),
                ('lp2_common_problems', models.JSONField(blank=True, default=list)),
                ('lp3_improvements_suggested', models.TextField(blank=True)),
                ('lp4_legal_challenges', models.JSONField(blank=True, default=dict)),
                ('lp5_portal_enhancements', models.TextField(blank=True)),
                ('ca1_training_received', models.CharField(blank=True, max_length=50)),
                ('ca1a_training_usefulness', models.CharField(blank=True, max_length=20)),
                ('ca2_psw_weboc_integration', models.CharField(blank=True, max_length=50)),
                ('ca3_common_challenges', models.TextField(blank=True)),
                ('ca4_policy_impact', models.CharField(blank=True, max_length=30)),
                ('ca5_psw_vs_weboc', models.CharField(blank=True, max_length=50)),
                ('final_remarks', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
