# Generated by Django 4.2.7 on 2025-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='lp2_other_text',
            field=models.TextField(blank=True),
        ),
    ]
