# Generated by Django 5.2.7 on 2025-10-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0001_relax_null_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca1_training",
            field=models.CharField(help_text="CA1: Training received", max_length=50),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca2_system_integration",
            field=models.CharField(
                help_text="CA2: System integration rating", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca3_challenges",
            field=models.JSONField(
                default=dict, help_text="CA3: Customs function challenges grid data"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca4_effectiveness",
            field=models.JSONField(
                default=dict, help_text="CA4: Process effectiveness grid data"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca5_policy_impact",
            field=models.CharField(
                help_text="CA5: Policy impact rating", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="ca6_biggest_challenge",
            field=models.CharField(
                help_text="CA6: Biggest operational challenge", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="g1_policy_impact",
            field=models.JSONField(
                default=dict,
                help_text="G1: Policy impact matrix (e.g., {'service_delivery': 'positive', ...})",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="g2_system_impact",
            field=models.JSONField(
                default=dict,
                help_text="G2: System impact matrix (e.g., {'workflow_efficiency': 'positive', ...})",
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="g3_technical_issues",
            field=models.CharField(
                help_text="G3: Frequency of technical issues (e.g., 'daily', 'never')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="g5_digital_literacy",
            field=models.CharField(
                help_text="G5: Digital literacy needs (e.g., 'neutral')", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="lp1_digital_support",
            field=models.CharField(
                help_text="LP1: Overall digital support rating", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="lp2_challenges",
            field=models.JSONField(
                default=dict, help_text="LP2: Representation challenges grid data"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="lp3_challenges",
            field=models.JSONField(
                default=dict, help_text="LP3: Compliance challenges grid data"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="lp4_challenges",
            field=models.JSONField(
                default=dict, help_text="LP4: Dispute resolution challenges grid data"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="lp5_tax_types",
            field=models.JSONField(
                default=dict, help_text="LP5: Tax-type impact for challenging functions"
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="professional_role",
            field=models.CharField(
                help_text="RI6: Professional role(s) as comma-separated values (e.g., 'legal', 'customs', 'legal,customs')",
                max_length=20,
            ),
        ),
    ]
