# Generated by Django 5.1.3 on 2025-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0002_surveyresponse_lp2_other_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyresponse",
            options={
                "ordering": ["-submission_date"],
                "verbose_name": "Survey Response",
                "verbose_name_plural": "Survey Responses",
            },
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca3_common_challenges",
            new_name="ca3_other_text",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="g8_training_received",
            new_name="ca4_duty_assessment",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca4_policy_impact",
            new_name="ca6_cargo_efficiency",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="lp3_improvements_suggested",
            new_name="ca9_feedback",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="lp5_portal_enhancements",
            new_name="ca9_other_text",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="lp4_legal_challenges",
            new_name="cross_system_answers",
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca3_procedure_challenges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca7_system_reliability",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca8_policy_impact",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca9_operational_challenges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g4_other_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g8_regional_differences",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g8_regional_differences_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp10_law_change_impact",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp11_adr_effectiveness",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp12_dispute_transparency",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp13_feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp13_overall_satisfaction",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp3_improvement_areas",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp3_other_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp4_other_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp4_other_income",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp4_other_procedure",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp4_other_sales",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp4_procedures",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp5_other_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp5_representation_challenges",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp6_filing_efficiency",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp7_case_tracking",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp8_notice_communication",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp9_law_accessibility",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
