# Generated by Django 5.2.7 on 2025-10-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0003_alter_surveyresponse_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca7_system_reliability",
            new_name="ca10_policy_impact",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca4_duty_assessment",
            new_name="ca11_client_representation",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca3_procedure_challenges",
            new_name="ca12_operational_challenges",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca3_other_text",
            new_name="ca12_other_text",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca5_psw_vs_weboc",
            new_name="ca13_biggest_challenge",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca9_feedback",
            new_name="ca13_other_text",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca9_other_text",
            new_name="ca4_other_text",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca9_operational_challenges",
            new_name="ca4_procedure_challenges",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="ca8_policy_impact",
            new_name="ca9_system_reliability",
        ),
        migrations.RenameField(
            model_name="surveyresponse",
            old_name="lp13_feedback",
            new_name="final_feedback",
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca3_psw_comparison",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca5_duty_assessment",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca7_document_verification",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="ca8_agency_coordination",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp10_qualitative_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp10_qualitative_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp6_qualitative_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp6_qualitative_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp8_qualitative_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="lp8_qualitative_visible",
            field=models.BooleanField(default=False),
        ),
    ]
