# Generated by Django 5.2.7 on 2025-10-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "survey",
            "0004_rename_ca7_system_reliability_surveyresponse_ca10_policy_impact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="kii_consent",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                help_text="RI10: Consent for follow-up interview (yes/no)",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="practice_areas",
            field=models.CharField(
                blank=True,
                help_text="RI7: Primary practice areas as comma-separated values (e.g., 'income_tax,sales_tax')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="district",
            field=models.CharField(
                help_text="RI5: District of residence (standard or custom)",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="email",
            field=models.EmailField(
                help_text="RI2: Respondent's email address", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="experience_customs",
            field=models.CharField(
                blank=True,
                help_text="RI9: Years of experience as Customs Agent (if applicable)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="experience_legal",
            field=models.CharField(
                blank=True,
                help_text="RI8: Years of experience as Legal Practitioner (if applicable)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="full_name",
            field=models.CharField(
                help_text="RI1: Respondent's full name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="mobile",
            field=models.CharField(
                blank=True, help_text="RI3: Mobile number (optional)", max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="professional_role",
            field=models.CharField(
                blank=True,
                help_text="RI6: Professional role(s) as comma-separated values (e.g., 'legal', 'customs', 'legal,customs')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="province",
            field=models.CharField(
                choices=[
                    ("ajk", "Azad Jammu and Kashmir"),
                    ("balochistan", "Balochistan"),
                    ("gb", "Gilgit-Baltistan"),
                    ("ict", "ICT"),
                    ("kpk", "Khyber Pakhtunkhwa"),
                    ("punjab", "Punjab"),
                    ("sindh", "Sindh"),
                ],
                help_text="RI4: Province of residence",
                max_length=20,
            ),
        ),
    ]
