# Generated by Django 5.2.7 on 2025-10-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_surveyresponse_kii_consent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g1_iris_rating",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g2_system_weaknesses",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g2a_weaknesses_details",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g3_iris_limitations",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g4_challenged_groups",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g4_other_text",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g5_clients_change",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g6_fee_change",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g7_digital_literacy_impact",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g8_regional_differences",
        ),
        migrations.RemoveField(
            model_name="surveyresponse",
            name="g8_regional_differences_text",
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g1_policy_impact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="G1: Policy impact matrix (e.g., {'service_delivery': 'positive', ...})",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g2_system_impact",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="G2: System impact matrix (e.g., {'workflow_efficiency': 'positive', ...})",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g3_technical_issues",
            field=models.CharField(
                blank=True,
                help_text="G3: Frequency of technical issues (e.g., 'daily', 'never')",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g4_disruption",
            field=models.CharField(
                blank=True,
                help_text="G4: Significance of disruptions (e.g., 'very_significantly', null if skipped)",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="g5_digital_literacy",
            field=models.CharField(
                blank=True,
                help_text="G5: Digital literacy needs (e.g., 'neutral')",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="kii_consent",
            field=models.CharField(
                blank=True,
                choices=[("yes", "Yes"), ("no", "No")],
                help_text="RI10: Consent for follow-up interview",
                max_length=3,
            ),
        ),
    ]
