# Generated by Django 5.2.7 on 2025-10-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0007_remove_surveyresponse_ca10_policy_impact_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="survey_feedback",
            field=models.TextField(
                blank=True,
                help_text="Feedback provided by the respondent on the survey questionnaire itself.",
            ),
        ),
    ]
